### PR TITLE
Added SDPi FHIR Gateway with the reference to the HL7 FHIR PoCD IG.

### PR DESCRIPTION
**Pull request by PeterKranich**
## 📑 Description

Added section SDPi FHIR Gateway in volume 2 under appendix B, which references to the HL7 FHIR PoCD implementation guide for the SDC to FHIR mapping.

## ☑ Mandatory Tasks

The following aspects have been respected by the pull request assignee and at least one reviewer:
  
- Changelog update (necessity checked and entry added or not added respectively)
  * [x] Pull Request Assignee
  * [x] Reviewer

### CODE REVIEW

**Comment by ToddCooper** [comment]
**SDPi Friday 2024.11.29 Review** - 

@riechkathrin - Please review the text to make sure it matches our discussion in the Developers #4 workshop.

**Review by riechkathrin — APPROVED** [review]

**Review by JavierEspina — APPROVED** [review]

**Comment by JavierEspina** [comment]
@ToddCooper, @d-gregorczyk - please review and (if happy) approve and merge. The review of Kathrin and me is no longer sufficient to unlock merging

**Review by ToddCooper — APPROVED** [review]
Reviewed and approved updates during SDPi Friday 2024.12.13 meeting.

**Review by JavierEspina — APPROVED** [review]
all fine

**Pull request merged**
