### PR TITLE
53 sdc to ihe dev gateway common section

### PR DESCRIPTION
**Pull request by PeterKranich**
## 📑 Description

The following has been changed:
* Moved the includes for the general HL7 segement and field mappings to the general section
* Set the sdpi_max_occurrence to 1 for the general requirements
* Replaced the includes in the DEC and ACM gateway mappings with the corresponding references in the general section

## ☑ Mandatory Tasks

The following aspects have been respected by the pull request assignee and at least one reviewer:
  
- Changelog update (necessity checked and entry added or not added respectively)
  * [x] Pull Request Assignee
  * [ ] Reviewer

### CODE REVIEW

**Comment by PeterKranich** [comment]
@d-gregorczyk: David, could you please check with your magic tool if the reference to the requirements for the general mappings are working now, and the section numbering works as expected.

**Comment by d-gregorczyk** [comment]
We should add a changelog entry for this substantial editorial work.

**Review by d-gregorczyk — COMMENTED** [review]
Looks good, no more requirement clashes in the document.

Nevertheless, I would suggest to introduce a general actor "SOMDS Gateway" or similar to have exactly one subject per requirement, which is easier for tools to digest. I can provide refactoring noone objects against the approach.

**Comment by PeterKranich** [comment]
> Nevertheless, I would suggest to introduce a general actor "SOMDS Gateway" or similar to have exactly one subject per requirement, which is easier for tools to digest. I can provide the refactoring if noone objects against the approach.

Agree - however, an IHE DEC/ACM gateway actor differs slightly from the IHE DoF gateway actor, and hence, the common mapping requirements will differ. So, do you think we need two actors for HL7 V2 based profiles and FHIR based profiles?

**Comment by d-gregorczyk** [comment]
Maybe - it depends if we can scope on another axis. For the moment, we stick to the current version and change/adjust actor names once we have decided on the actor renaming, see #178.

I also added a changelog entry. This can be merged now.

**Review by d-gregorczyk — APPROVED** [review]

**Pull request merged**
