### PR TITLE
Release 1.3.0

### PR DESCRIPTION
**Pull request by d-gregorczyk**

### CODE REVIEW

**Review by JavierEspina — CHANGES_REQUESTED** [review]
Good changes to update to 1.3 in the CHANGELOG and front-matter. HOWEVER there are still many places that talk about 1.2 such as the "Introduction to this Supplement" and several "SDPi Supplement Version Notes" (e.g., in 1.2.3.13, 1.10.1, etc, etc.). The best way to catch all that is to search the doc for "1.2"

**Comment by JavierEspina** [comment]
> Good changes to update to 1.3 in the CHANGELOG and front-matter. HOWEVER there are still many places that talk about 1.2 such as the "Introduction to this Supplement" and several "SDPi Supplement Version Notes" (e.g., in 1.2.3.13, 1.10.1, etc, etc.). The best way to catch all that is to search the doc for "1.2"

That´s I least what I can see in the package that you built some hours ago, which I just downloaded from _Actions_

**Comment by ToddCooper** [comment]
@JavierEspina  - at this point, I agree but think that this will probably need to be a 1.3.1 update.  (quick fixes, like what you pointed out).  Given that the Release 1.3.0 is already tagged and out there, it doesn't make much sense (unless I'm missing something) to go through, change, retag, etc.  So I propose: Merge it as is and immediately (Monday) we can do a 1.3.1 with these corrections.

**Review by JavierEspina — APPROVED** [review]
Changes look good. Missing editorial changes related to correct version numbering will be updated in a minor corrigendum version 1.3.1

**Comment by d-gregorczyk** [comment]
We need these editorial changes to be captured somewhere. Do we have a ticket for that?

**Comment by ToddCooper** [comment]
@d-gregorczyk -- Added a new issue:  #282

**Pull request merged**
