### PR TITLE
Corrected SDPi-A PUML Example File

### PR DESCRIPTION
**Pull request by ToddCooper**
Corrected reference in 1:12.1.1-1 to the correct file name.

Closes # 

## 📑 Description
#135

### CODE REVIEW

**Review by kenjfuchs — APPROVED** [review]
Reviewed

**Comment by d-gregorczyk** [comment]
@ToddCooper As this goes into 1.1, you now have to provide a changelog entry in the changelog.md file.

**Comment by ToddCooper** [comment]
> 

@d-gregorczyk  Actually, this goes into 1.0.1 ... this (as well as the other two) are fixes and not related to "minor" enhancements.  That said, HOW do you change the changelog.md AFTER a merge has completed.  I added the line to this branch (couldn't do it to master directly, which is a good thing), but do I now have to "revert", update, re-merge?

**Comment by d-gregorczyk** [comment]
Do we release fix versions? So far (and according to the current wiki), there is only major and minor versions being addressed as we are lacking information regarding the scope of fixes. That's why I omitted a "fixed" section from the changelog.md in the first place.

We can add it at any time, but it only makes life more complicated. Having major releases for anything that causes implementations to break compatability and minor for things that do not break compatability is sufficient imho.

**Comment by ToddCooper** [comment]
@d-gregorczyk  OK ... but right now ... you have fixes that are labeled 1.1 that IMHO are really 1.0.1 and should be published (revision 1.0.1) ASAP.  Honestly I don't care what goes into the changelog.md in terms of major vs. minor vs. incremental, though of course, we ALWAYS want there to be a changelog for major / minor.  

+ I am updating the wiki article to add the "fix" version process, as we discussed previously. 

Clearly I'm missing something here and perhaps an early Tuesday call (early Todd time) would be helpful ...

**Comment by d-gregorczyk** [comment]
If we choose to publish fix versions, then let's add a Fixed section to the changelog. It's as easy as that. We can move my changelog entries together with your one.

The advantage of maintaining a changelog.md file is that it provides all the benefits of the git versioning. We can always adapt it to our needs.

**Pull request merged**
